### ISSUE TITLE
How to setting allow_delete_body option is true？

### ISSUE THREAD

**Issue by zengzhengrong** [utrack/clay#89]
I want to allow delete request have a request body , but I don't konw how to setting ,
I use yaml to config my http define ,

```
--goclay_out: must not set request body when http method is DELETE except allow_delete_body option is true: DeleteUser
```
```
http:
  rules:
  -  selector: user_center.ManageUserCenter.DeleteUser
      delete: '/v1/example/userCenter/deleteUser'
      body: 'data'
      allow_delete_body: true
```
it does not work
